version: '3.4'

networks:
  kong-net:
  keycloak-net:

volumes:
  kong-datastore:
  keycloak-datastore:
  keycloak-tls:

services:
  kong:
    build:
      context: ./
    image: kong-oidc:latest
    networks:
      - kong-net
    ports:
      - "80:80"       # Listener
      - "8001:8001"   # Admin API
      - "443:8443"    # Listener  (SSL)
      - "8444:8444"   # Admin API (SSL)
    environment:
      KONG_DATABASE:         postgres
      KONG_PG_HOST:          10.4.0.2
      KONG_PG_PORT:          15432
      KONG_PG_DATABASE:      api-gw
      KONG_PG_USER:          kong
      KONG_PG_PASSWORD:      kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG:  /dev/stderr
      KONG_ADMIN_ERROR_LOG:  /dev/stderr
      KONG_PROXY_LISTEN:     0.0.0.0:80, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN:     0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PLUGINS:          bundled,oidc
      KONG_LOG_LEVEL:        debug
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 512k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 512k

  konga:
    image: pantsel/konga:0.14.7
    depends_on:
      - kong
    networks:
      - kong-net
    ports:
      - "1337:1337"        # konga
    environment:
      DB_ADAPTER: postgres
      DB_HOST: 10.4.0.2    # kong-db
      DB_PORT: 15432       # '5432'
      DB_USER: kong
      DB_PASSWORD: kong
      DB_DATABASE: api-gw
      NODE_ENV: development

  keycloak:
    image: jboss/keycloak:14.0.0
    depends_on:
      - konga
    networks:
      - keycloak-net
    ports:
      - "8180:8080"
      - "8443:8443"
    environment:
      DB_VENDOR:   POSTGRES
      DB_ADDR:     10.4.0.2          # keycloak-db
      DB_PORT:     25432             # 5432
      DB_DATABASE: keycloak
      DB_USER:     keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER:     admin
      KEYCLOAK_PASSWORD: Paywallet@123
      PROXY_ADDRESS_FORWARDING: 'true'
    volumes:
      - keycloak-tls:/etc/x509/https
